const cds = require('@sap/cds');
const axios = require('axios');

const S4_MOCK_URL = 'http://localhost:8080/sap/opu/odata/sap';
const ORCHESTRATOR_URL = 'http://localhost:8000/orchestrate';

module.exports = cds.service.impl(async function() {
    this.on('triggerDisruption', async (req) => {
        try {
            const { supplierId, materialId } = req.data;
            const cds_utils = cds.utils;
            const disruptionId = cds_utils.uuid();
            
            console.log(`[CAP] Triggered for ${supplierId}, ${materialId} - Generated ID: ${disruptionId}`);
            
            // Log to Audit
            await INSERT.into('foresight.AuditEvent', {
                entityName: 'Supplier',
                entityId: supplierId,
                eventType: 'DISRUPTION_TRIGGERED',
                details: `Supplier ${supplierId} failed for material ${materialId}`
            });

            // Create Disruption
            await INSERT.into('foresight.Disruption', {
                ID: disruptionId,
                type: 'SupplierFailure',
                description: 'Critical supplier went offline due to cyberattack',
                status: 'ANALYZING',
                confidenceScore: 0.95,
                impactedSupplier_ID: supplierId,
                impactedMaterial_ID: materialId
            });

            console.log(`[CAP] Fetching context from Mock S/4HANA for ${supplierId}, ${materialId}`);
            
            // 1. Fetch from S/4
            const suppliersRes = await axios.get(`${S4_MOCK_URL}/API_SUPPLIER/A_Supplier`);
            const inventoryRes = await axios.get(`${S4_MOCK_URL}/API_MATERIAL_STOCK_SRV/A_MaterialStock`);
            
            const availableSuppliers = suppliersRes.data.d.results;
            const availableInventory = inventoryRes.data.d.results;
            
            const context = {
                disruption_id: disruptionId,
                impacted_material_id: materialId,
                impacted_supplier_id: supplierId,
                required_quantity: 5000,
                deadline: "2026-10-15",
                available_suppliers: availableSuppliers,
                available_inventory: availableInventory
            };

            const raw_event = {
                id: disruptionId,
                type: "SupplierFailure"
            };

            console.log(`[CAP] Calling Python Orchestrator...`);
            const orchestratorRes = await axios.post(ORCHESTRATOR_URL, {
                raw_event,
                context
            });
            
            const plan = orchestratorRes.data;
            console.log(`[CAP] Received Plan from Orchestrator with ${plan.actions ? plan.actions.length : 0} actions.`);

            // 2. Create Recovery Plan
            const customPlanId = cds_utils.uuid();
            
            await INSERT.into('foresight.RecoveryPlan', {
                ID: customPlanId,
                disruption_ID: disruptionId,
                status: plan.validation && plan.validation.requires_human_approval ? 'PENDING_APPROVAL' : 'APPROVED',
                totalCost: plan.total_cost || 0,
                serviceImpact: 'Minimal',
                commitmentRisk: plan.commitment_risk || 0.0,
                rationale: 'Generated by FORESIGHT AI Swarm'
            });
            
            // Insert Actions
            if (plan.actions && plan.actions.length > 0) {
                const actionsToInsert = plan.actions.map(action => ({
                    ID: cds_utils.uuid(),
                    recoveryPlan_ID: customPlanId,
                    agentName: action.agent_name,
                    actionType: action.action_type,
                    targetSupplier_ID: action.action_type === 'CREATE_PO' ? action.target_id : null,
                    targetPlant_ID: action.action_type === 'STOCK_TRANSFER' ? action.target_id : null,
                    quantity: action.quantity,
                    estimatedCost: action.cost,
                    description: `Action from ${action.agent_name}`
                }));
                await INSERT.into('foresight.AgentAction', actionsToInsert);
            }

            // Update Disruption
            await UPDATE('foresight.Disruption').set({ status: 'PLAN_PROPOSED', recoveryPlan_ID: customPlanId }).where({ ID: disruptionId });

            return await SELECT.one.from('foresight.Disruption').where({ ID: disruptionId });

        } catch (error) {
            console.error("[CAP] CRITICAL ERROR IN triggerDisruption:", error.stack || error.message);
            throw error;
        }
    });

    this.on('approvePlan', async (req) => {
        const { planId, approverId, comments } = req.data;

        // Update Recovery Plan Status
        await UPDATE('foresight.RecoveryPlan').set({ status: 'APPROVED' }).where({ ID: planId });

        // Add Approval record
        await INSERT.into('foresight.Approval', {
            recoveryPlan_ID: planId,
            approverId: approverId,
            decision: 'APPROVED',
            comments: comments
        });

        // Log Audit Event
        await INSERT.into('foresight.AuditEvent', {
            entityName: 'RecoveryPlan',
            entityId: planId,
            eventType: 'PLAN_APPROVED',
            details: `Plan approved by ${approverId}: ${comments}`
        });

        // Execute actions against S/4 Mock
        try {
            const actions = await SELECT.from('foresight.AgentAction').where({ recoveryPlan_ID: planId });
            for (let action of actions) {
                if (action.actionType === 'CREATE_PO') {
                    console.log(`[CAP] Executing PO Creation for ${action.targetSupplier_ID}...`);
                    await axios.post(`${S4_MOCK_URL}/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrder`, {
                        Supplier: action.targetSupplier_ID,
                        Material: 'MAT-100',
                        OrderQuantity: action.quantity
                    });
                }
            }
            
            // Mark as executed
            await UPDATE('foresight.RecoveryPlan').set({ status: 'EXECUTED' }).where({ ID: planId });
            
            await INSERT.into('foresight.AuditEvent', {
                entityName: 'RecoveryPlan',
                entityId: planId,
                eventType: 'EXECUTION_SUCCESS',
                details: `Plan ${planId} successfully executed against S/4HANA.`
            });

        } catch (error) {
            console.error("[CAP] Execution Failed:", error.message);
            await UPDATE('foresight.RecoveryPlan').set({ status: 'EXECUTION_FAILED' }).where({ ID: planId });
            
            await INSERT.into('foresight.AuditEvent', {
                entityName: 'RecoveryPlan',
                entityId: planId,
                eventType: 'EXECUTION_FAILED',
                details: `Plan ${planId} execution failed: ${error.message}`
            });
        }

        return await SELECT.one.from('foresight.RecoveryPlan').where({ ID: planId });
    });
});
