const cds = require('@sap/cds');
const axios = require('axios');

const S4_MOCK_URL = 'http://localhost:8080/sap/opu/odata/sap';
const ORCHESTRATOR_URL = 'http://localhost:8000/orchestrate';

module.exports = cds.service.impl(async function() {
    this.on('triggerDisruption', async (req) => {
        try {
            const { supplierId, materialId } = req.data;
            const cds_utils = cds.utils;
            const disruptionId = cds_utils.uuid();
            
            console.log(`[CAP] Triggered for ${supplierId}, ${materialId} - Generated ID: ${disruptionId}`);
            
            // Log to Audit
            await INSERT.into('foresight.AuditEvent', {
                entityName: 'Supplier',
                entityId: supplierId,
                eventType: 'DISRUPTION_TRIGGERED',
                details: `Supplier ${supplierId} failed for material ${materialId}`
            });

            // Create Disruption
            await INSERT.into('foresight.Disruption', {
                ID: disruptionId,
                type: 'SupplierFailure',
                description: 'Critical supplier went offline due to cyberattack',
                status: 'ANALYZING',
                confidenceScore: 0.95,
                impactedSupplier_ID: supplierId,
                impactedMaterial_ID: materialId
            });

            console.log(`[CAP] Fetching context from Mock S/4HANA for ${supplierId}, ${materialId}`);
            
            // 1. Fetch from S/4
            const suppliersRes = await axios.get(`${S4_MOCK_URL}/API_SUPPLIER/A_Supplier`);
            const inventoryRes = await axios.get(`${S4_MOCK_URL}/API_MATERIAL_STOCK_SRV/A_MaterialStock`);
            
            const availableSuppliers = suppliersRes.data.d.results;
            const availableInventory = inventoryRes.data.d.results;
            
            const context = {
                disruption_id: disruptionId,
                impacted_material_id: materialId,
                impacted_supplier_id: supplierId,
                required_quantity: 5000,
                deadline: "2026-10-15",
                available_suppliers: availableSuppliers,
                available_inventory: availableInventory
            };

            const raw_event = {
                id: disruptionId,
                type: "SupplierFailure"
            };

            console.log(`[CAP] Calling Python Orchestrator...`);
            const orchestratorRes = await axios.post(ORCHESTRATOR_URL, {
                raw_event,
                context
            });
            
            const plan = orchestratorRes.data;
            console.log(`[CAP] Received Plan from Orchestrator with ${plan.actions ? plan.actions.length : 0} actions.`);

            // 2. Create Recovery Plan
            const customPlanId = cds_utils.uuid();
            
            await INSERT.into('foresight.RecoveryPlan', {
                ID: customPlanId,
                disruption_ID: disruptionId,
                status: plan.validation && plan.validation.requires_human_approval ? 'PENDING_APPROVAL' : 'APPROVED',
                totalCost: plan.total_cost || 0,
                serviceImpact: 'Minimal',
                commitmentRisk: plan.commitment_risk || 0.0,
                rationale: 'Generated by FORESIGHT AI Swarm'
            });
            
            // Insert Actions
            if (plan.actions && plan.actions.length > 0) {
                const actionsToInsert = plan.actions.map(action => ({
                    ID: cds_utils.uuid(),
                    recoveryPlan_ID: customPlanId,
                    agentName: action.agent_name,
                    actionType: action.action_type,
                    targetSupplier_ID: action.action_type === 'CREATE_PO' ? action.target_id : null,
                    targetPlant_ID: action.action_type === 'STOCK_TRANSFER' ? action.target_id : null,
                    quantity: action.quantity,
                    estimatedCost: action.cost,
                    description: `Action from ${action.agent_name}`
                }));
                await INSERT.into('foresight.AgentAction', actionsToInsert);
            }

            // Create Initial Commitment Record
            await INSERT.into('foresight.Commitment', {
                ID: cds_utils.uuid(),
                recoveryPlan_ID: customPlanId,
                commitmentType: 'CustomerOrder',
                referenceId: 'CUST-882 (Automotive Tier 1)',
                status: 'AT_RISK'
            });

            // Update Disruption
            await UPDATE('foresight.Disruption').set({ status: 'PLAN_PROPOSED', recoveryPlan_ID: customPlanId }).where({ ID: disruptionId });

            return await SELECT.one.from('foresight.Disruption').where({ ID: disruptionId });

        } catch (error) {
            console.error("[CAP] CRITICAL ERROR IN triggerDisruption:", error.stack || error.message);
            throw error;
        }
    });

    this.on('approvePlan', async (req) => {
        const { planId, approverId, comments } = req.data;
        const cds_utils = cds.utils;
        const reviewer = approverId || 'SC_Ops_Executive';
        const notes = comments || 'Executive approved recovery plan.';

        // Update Recovery Plan Status
        await UPDATE('foresight.RecoveryPlan').set({ status: 'APPROVED' }).where({ ID: planId });

        // Add Approval record
        await INSERT.into('foresight.Approval', {
            ID: cds_utils.uuid(),
            recoveryPlan_ID: planId,
            approverId: reviewer,
            decision: 'APPROVED',
            comments: notes
        });

        // Log Audit Event
        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'RecoveryPlan',
            entityId: planId,
            eventType: 'PLAN_APPROVED',
            details: `Plan approved by ${reviewer}: ${notes}`
        });

        // Execute actions against S/4 Mock
        try {
            const actions = await SELECT.from('foresight.AgentAction').where({ recoveryPlan_ID: planId });
            for (let action of actions) {
                if (action.actionType === 'CREATE_PO') {
                    console.log(`[CAP] Executing PO Creation for ${action.targetSupplier_ID}...`);
                    await axios.post(`${S4_MOCK_URL}/API_PURCHASEORDER_PROCESS_SRV/A_PurchaseOrder`, {
                        Supplier: action.targetSupplier_ID,
                        Material: 'MAT-100',
                        OrderQuantity: action.quantity
                    });
                }
            }
            
            // Mark as executed & mitigate commitments
            await UPDATE('foresight.RecoveryPlan').set({ status: 'EXECUTED' }).where({ ID: planId });
            await UPDATE('foresight.Commitment').set({ status: 'MITIGATED' }).where({ recoveryPlan_ID: planId });
            
            await INSERT.into('foresight.AuditEvent', {
                ID: cds_utils.uuid(),
                entityName: 'RecoveryPlan',
                entityId: planId,
                eventType: 'EXECUTION_SUCCESS',
                details: `Plan ${planId} successfully executed against S/4HANA.`
            });

        } catch (error) {
            console.error("[CAP] Execution Failed:", error.message);
            await UPDATE('foresight.RecoveryPlan').set({ status: 'EXECUTION_FAILED' }).where({ ID: planId });
            
            await INSERT.into('foresight.AuditEvent', {
                ID: cds_utils.uuid(),
                entityName: 'RecoveryPlan',
                entityId: planId,
                eventType: 'EXECUTION_FAILED',
                details: `Plan ${planId} execution failed: ${error.message}`
            });
        }

        return await SELECT.one.from('foresight.RecoveryPlan').where({ ID: planId });
    });

    this.on('rejectPlan', async (req) => {
        const { planId, approverId, comments } = req.data;
        const cds_utils = cds.utils;
        const reviewer = approverId || 'SC_Ops_Executive';
        const notes = comments || 'Plan rejected by operations executive. Holds released.';

        // 1. Update Recovery Plan Status to REJECTED
        await UPDATE('foresight.RecoveryPlan').set({ status: 'REJECTED' }).where({ ID: planId });

        // 2. Add Approval record
        await INSERT.into('foresight.Approval', {
            ID: cds_utils.uuid(),
            recoveryPlan_ID: planId,
            approverId: reviewer,
            decision: 'REJECTED',
            comments: notes
        });

        // 3. Log Audit Event
        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'RecoveryPlan',
            entityId: planId,
            eventType: 'PLAN_REJECTED',
            details: `Plan ${planId} rejected by ${reviewer}: ${notes}`
        });

        // 4. SAGA Compensation
        await UPDATE('foresight.RecoveryPlan').set({ status: 'COMPENSATING' }).where({ ID: planId });
        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'SagaCoordinator',
            entityId: planId,
            eventType: 'SAGA_COMPENSATION',
            details: 'Released temporary inventory reservations (1,200 PC at Plant B) and cancelled pending purchase order drafts.'
        });

        // 5. Replan Initiated
        await UPDATE('foresight.RecoveryPlan').set({ status: 'REPLANNED' }).where({ ID: planId });
        await UPDATE('foresight.Commitment').set({ status: 'FAILED' }).where({ recoveryPlan_ID: planId });
        
        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'RecoveryPlan',
            entityId: planId,
            eventType: 'REPLAN_INITIATED',
            details: 'Recovery replanning initiated. Agent Swarm notified to formulate secondary recovery alternatives.'
        });

        return await SELECT.one.from('foresight.RecoveryPlan').where({ ID: planId });
    });

    this.on('failExecution', async (req) => {
        const { planId, reason } = req.data;
        const cds_utils = cds.utils;
        const failReason = reason || 'Mock S/4HANA communication timeout or credit limit check failed.';

        await UPDATE('foresight.RecoveryPlan').set({ status: 'EXECUTION_FAILED' }).where({ ID: planId });
        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'RecoveryPlan',
            entityId: planId,
            eventType: 'EXECUTION_FAILED',
            details: `S/4HANA commit execution failed: ${failReason}`
        });

        // Trigger SAGA Compensation
        await UPDATE('foresight.RecoveryPlan').set({ status: 'COMPENSATING' }).where({ ID: planId });
        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'SagaCoordinator',
            entityId: planId,
            eventType: 'SAGA_COMPENSATION',
            details: 'Automated failure compensation: rolled back staged reservations.'
        });

        await UPDATE('foresight.RecoveryPlan').set({ status: 'REPLANNED' }).where({ ID: planId });
        await UPDATE('foresight.Commitment').set({ status: 'FAILED' }).where({ recoveryPlan_ID: planId });

        await INSERT.into('foresight.AuditEvent', {
            ID: cds_utils.uuid(),
            entityName: 'RecoveryPlan',
            entityId: planId,
            eventType: 'REPLAN_INITIATED',
            details: 'Automated replan initiated following execution failure.'
        });

        return await SELECT.one.from('foresight.RecoveryPlan').where({ ID: planId });
    });
});
